server:
  port: 8081
spring:
  application:
    name: tweet-service
  data:
    mongodb:
      database: tweet
      port: 27017
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest