server:
  port: 8082
spring:
  application:
    name: user
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/user
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    addresses: amqp://rabbitmq:5672