name: e2e-test

on: workflow_dispatch

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          repository: abevdwerf/Kwetter-frontend
          path: Kwetter-frontend

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run config
          build: npm run build
          start: npm start
          working-directory: Kwetter-frontend
          spec: cypress/e2e/post_tweet.cy.ts
          
      - name: Stop Docker Compose
        run: docker-compose down
