name: e2e-test

on: workflow_dispatch

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          repository: abevdwerf/Kwetter-frontend
          path: Kwetter-frontend

      - name: Start Docker Compose
        run: docker-compose up -d
      - name: docker inspect
        run: docker inspect api-gateway
      - name: docker ps list
        run: docker ps

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run config | npm run build
          start: npm start
          wait-on: 'http://[::1]:4200'
          working-directory: Kwetter-frontend
          spec: cypress/e2e/post_tweet.cy.ts
          record: true
        env:
          FIREBASE_DETAILS: ${{ secrets.FIRE_BASE_DETAILS }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Stop Docker Compose
        run: docker-compose down
